-- PostgreSQL schema for VINLEARN / VinLearn.
-- Run:
--   psql "$VINLEARN_DATABASE_URL" -f postgres_schema.sql
--
-- The app can also create these tables automatically via SQLAlchemy on startup.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(200) NOT NULL,
    password_hash varchar(255) NOT NULL,
    full_name varchar(120) NOT NULL,
    organization varchar(160),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS courses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title varchar(200) NOT NULL,
    description text NOT NULL DEFAULT '',
    subject varchar(120) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    archived boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS slides (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id integer NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    index integer NOT NULL,
    title varchar(300) NOT NULL DEFAULT '',
    blocks jsonb NOT NULL DEFAULT '[]'::jsonb,
    source varchar(16) NOT NULL DEFAULT 'manual',
    notes text NOT NULL DEFAULT '',
    page_image varchar(255) NOT NULL DEFAULT '',
    CONSTRAINT uq_slide_course_index UNIQUE (course_id, index)
);

CREATE TABLE IF NOT EXISTS checkpoints (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slide_id integer NOT NULL REFERENCES slides(id) ON DELETE CASCADE,
    label varchar(160) NOT NULL DEFAULT '',
    goal text NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_checkpoints_slide_id UNIQUE (slide_id)
);

CREATE TABLE IF NOT EXISTS questions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkpoint_id integer NOT NULL REFERENCES checkpoints(id) ON DELETE CASCADE,
    position integer NOT NULL DEFAULT 0,
    type varchar(32) NOT NULL,
    prompt text NOT NULL,
    options jsonb NOT NULL DEFAULT '[]'::jsonb,
    answer jsonb NOT NULL DEFAULT '{}'::jsonb,
    origin varchar(16) NOT NULL DEFAULT 'manual'
);

CREATE TABLE IF NOT EXISTS rooms (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id integer NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    code varchar(8) NOT NULL,
    name varchar(200) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_rooms_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id integer NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    title varchar(200) NOT NULL DEFAULT '',
    started_at timestamptz NOT NULL DEFAULT now(),
    ended_at timestamptz,
    current_slide_index integer NOT NULL DEFAULT 0,
    current_question_id integer REFERENCES questions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS participants (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    token varchar(64) NOT NULL,
    display_name varchar(60) NOT NULL,
    avatar varchar(16) NOT NULL DEFAULT 'paw',
    joined_at timestamptz NOT NULL DEFAULT now(),
    online boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_participants_token UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS answers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id integer NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    slide_index integer NOT NULL DEFAULT 0,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    correct boolean,
    score double precision NOT NULL DEFAULT 0.0,
    response_ms integer NOT NULL DEFAULT 0,
    skipped boolean NOT NULL DEFAULT false,
    confidence integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS learning_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id integer REFERENCES participants(id) ON DELETE SET NULL,
    slide_index integer NOT NULL DEFAULT 0,
    type varchar(32) NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS advices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    slide_index integer NOT NULL DEFAULT 0,
    state varchar(32) NOT NULL,
    should_alert boolean NOT NULL DEFAULT false,
    headline varchar(200) NOT NULL DEFAULT '',
    action text NOT NULL DEFAULT '',
    evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    confidence varchar(16) NOT NULL DEFAULT 'low',
    source varchar(24) NOT NULL DEFAULT 'rule_fallback',
    metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    feedback varchar(16),
    feedback_note text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS student_hints (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id integer NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    slide_index integer NOT NULL DEFAULT 0,
    questions jsonb NOT NULL DEFAULT '[]'::jsonb,
    source varchar(16) NOT NULL DEFAULT 'rule_fallback',
    picked text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS support_questions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id integer NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    slide_index integer NOT NULL DEFAULT 0,
    text text NOT NULL,
    confusion_score double precision NOT NULL DEFAULT 0.0,
    classifier_source varchar(24) NOT NULL DEFAULT 'rule_fallback',
    escalated boolean NOT NULL DEFAULT false,
    status varchar(24) NOT NULL DEFAULT 'pending',
    answer_text text,
    answered_by varchar(24),
    answer_disclaimer text,
    created_at timestamptz NOT NULL DEFAULT now(),
    answered_at timestamptz
);

CREATE INDEX IF NOT EXISTS ix_users_email ON users(email);
CREATE INDEX IF NOT EXISTS ix_courses_owner_id ON courses(owner_id);
CREATE INDEX IF NOT EXISTS ix_slides_course_id ON slides(course_id);
CREATE INDEX IF NOT EXISTS ix_checkpoints_slide_id ON checkpoints(slide_id);
CREATE INDEX IF NOT EXISTS ix_questions_checkpoint_id ON questions(checkpoint_id);
CREATE INDEX IF NOT EXISTS ix_rooms_owner_id ON rooms(owner_id);
CREATE INDEX IF NOT EXISTS ix_rooms_course_id ON rooms(course_id);
CREATE INDEX IF NOT EXISTS ix_rooms_code ON rooms(code);
CREATE INDEX IF NOT EXISTS ix_sessions_room_id ON sessions(room_id);
CREATE INDEX IF NOT EXISTS ix_participants_session_id ON participants(session_id);
CREATE INDEX IF NOT EXISTS ix_participants_token ON participants(token);
CREATE INDEX IF NOT EXISTS ix_answers_session_id ON answers(session_id);
CREATE INDEX IF NOT EXISTS ix_answers_question_id ON answers(question_id);
CREATE INDEX IF NOT EXISTS ix_learning_events_session_id ON learning_events(session_id);
CREATE INDEX IF NOT EXISTS ix_advices_session_id ON advices(session_id);
CREATE INDEX IF NOT EXISTS ix_student_hints_session_id ON student_hints(session_id);
CREATE INDEX IF NOT EXISTS ix_student_hints_participant_id ON student_hints(participant_id);
CREATE INDEX IF NOT EXISTS ix_support_questions_session_id ON support_questions(session_id);
CREATE INDEX IF NOT EXISTS ix_support_questions_participant_id ON support_questions(participant_id);

COMMIT;
